---
name: "Initialize issue in project"
on:
  issues:
    types:
      - opened

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      # 1) Extract just the YYYY-MM-DD part of the issue’s created_at timestamp
      - name: Extract issue creation date
        id: extract
        run: |
          # payload has created_at like "2025-04-29T14:23:05Z"
          created=$(echo "${{ github.event.issue.created_at }}" | cut -d'T' -f1)
          echo "Extracted date: $created"
          echo "date=$created" >> $GITHUB_OUTPUT

      # 2) Optionally set a Status single-select in your Project
      - name: Set issue Status to "Backlog"
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/VakuumimKopf/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          field-name: Status
          field-value: Backlog

      # 3) Set your Start Date field to the extracted creation date
      - name: Set Start Date
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/VakuumimKopf/projects/3
          github-token: ${{ secrets.GITHUB_TOKEN }}
          field-name: Start date
          field-value: ${{ steps.extract.outputs.date }}
