name: Issue Automation

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  add_to_project_and_update_fields:
    runs-on: ubuntu-latest
    steps:
    - name: Add issue to project and set fields
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Extract issue details
        ISSUE_NODE_ID=$(jq -r '.issue.node_id' "$GITHUB_EVENT_PATH")
        CREATED_AT=$(jq -r '.issue.created_at' "$GITHUB_EVENT_PATH")
        START_DATE=$(date -u -d "$CREATED_AT" +"%Y-%m-%d")

        # Add debug logs
        echo "Issue Node ID: $ISSUE_NODE_ID"
        echo "Created At: $CREATED_AT"
        echo "Start Date: $START_DATE"

        # Replace PROJECT_ID, START_DATE_FIELD_ID, and STATUS_FIELD_ID with your actual IDs
        GRAPHQL_QUERY=$(cat <<EOF
        mutation {
          addProjectV2ItemById(input: {projectId: "PVT_kwHOCQXJ6M4A2N9V", contentId: "$ISSUE_NODE_ID"}) {
            item {
              id
            }
          }
          updateProjectV2ItemFieldValue(
            input: {
              projectId: "PVT_kwHOCQXJ6M4A2N9V",
              itemId: "$ISSUE_NODE_ID",
              fieldId: "PVTF_lAHOCQXJ6M4A2N9Vzgrj4tQ",
              value: "$START_DATE"
            }
          ) {
            projectV2Item {
              id
            }
          }
          updateProjectV2ItemFieldValue(
            input: {
              projectId: "PVT_kwHOCQXJ6M4A2N9V",
              itemId: "$ISSUE_NODE_ID",
              fieldId: "PVTSSF_lAHOCQXJ6M4A2N9Vzgrj4ds",
              value: "Backlog"
            }
          ) {
            projectV2Item {
              id
            }
          }
        }
        EOF
        )

        # Debug the GraphQL query
        echo "GraphQL Query: $GRAPHQL_QUERY"

        # Execute GraphQL query and log the response
        RESPONSE=$(curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d "{\"query\":\"$GRAPHQL_QUERY\"}" \
          https://api.github.com/graphql)
        
        echo "GraphQL Response: $RESPONSE"
