name: ROS 2 CI
 
on:
  push:
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          path: workspace
          
      - name: Setup workspace
        uses: ichiro-its/ros2-ws-action/setup@v1.0.0
        with:
          distro: humble
        
      - name: Build workspace
        uses: ichiro-its/ros2-ws-action/build@v1.0.0
        with:
          distro: humble
